"use client";

import Link from "next/link";
import { Button } from "@/components/ui/Button";

export default function TermsAndConditions() {
    return (
        <main className="min-h-screen bg-white">
            {/* Simple Header */}
            <div className="border-b-2 border-black p-6 bg-primary">
                <div className="max-w-4xl mx-auto flex justify-between items-center">
                    <Link href="/" className="flex items-center gap-2">
                        <div className="w-8 h-8 border border-black bg-white">
                            <img src="/logo.png" alt="NCET Buddy" className="w-full h-full object-cover" />
                        </div>
                        <span className="text-xl font-bold text-black uppercase">NCET Buddy</span>
                    </Link>
                    <Link href="/">
                        <Button variant="secondary" className="bg-black text-white text-sm px-4 py-2">Go Home</Button>
                    </Link>
                </div>
            </div>

            <div className="max-w-4xl mx-auto py-16 px-6">
                {/* Page Title */}
                <div className="mb-12">
                    <h1 className="text-4xl font-black text-black uppercase mb-2">Terms and Conditions</h1>
                    <div className="h-1 w-32 bg-primary mt-4"></div>
                    <p className="mt-6 text-xs text-black/60 font-bold uppercase">Last Updated: January 2026</p>
                </div>

                {/* Content */}
                <div className="space-y-6 text-black text-sm leading-relaxed">
                    <p>
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>

                    <p>
                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong>www.ncetbuddy.in</strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                    </p>

                    <p>
                        The Platform is owned by <strong>ExamBuddy</strong>, a company incorporated under the Companies Act, 1956 with its registered office at <strong>KOLKATA</strong> (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                    </p>

                    <p>
                        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
                    </p>

                    <div className="p-6 bg-primary/20 border-l-4 border-primary my-8">
                        <p className="text-sm font-bold uppercase">
                            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                        </p>
                    </div>

                    <h2 className="text-xl font-black uppercase mt-10 mb-4">Terms of Use</h2>

                    <div className="space-y-4">
                        <div>
                            <p className="font-bold mb-1">1.</p>
                            <p>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">2.</p>
                            <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">3.</p>
                            <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">4.</p>
                            <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">5.</p>
                            <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">6.</p>
                            <p>You agree to pay us the charges associated with availing the Services.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">7.</p>
                            <p>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">8.</p>
                            <p>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">9.</p>
                            <p>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">10.</p>
                            <p>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">11.</p>
                            <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">12.</p>
                            <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">13.</p>
                            <p>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Kolkata.</p>
                        </div>

                        <div>
                            <p className="font-bold mb-1">14.</p>
                            <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
                        </div>
                    </div>
                </div>

                {/* Simple CTA */}
                <div className="mt-16 pt-8 border-t-2 border-black/10 text-center">
                    <Link href="/">
                        <Button className="bg-primary text-black font-bold px-8 py-3 uppercase text-sm">
                            I Understand
                        </Button>
                    </Link>
                </div>
            </div>
        </main>
    );
}
