"use client";

import Link from "next/link";
import { Button } from "@/components/ui/Button";

export default function TermsAndConditions() {
    return (
        <main className="min-h-screen bg-white">
            {/* Header */}
            <div className="border-b-4 border-black p-6 flex justify-between items-center bg-primary">
                <Link href="/" className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg overflow-hidden border-2 border-black bg-white">
                        <img src="/logo.png" alt="NCET Buddy" className="w-full h-full object-cover" />
                    </div>
                    <span className="text-2xl font-black text-black uppercase italic tracking-tighter">NCET Buddy</span>
                </Link>
                <Link href="/">
                    <Button variant="secondary" className="bg-black text-white hover:bg-white hover:text-black transition-all">Go Home</Button>
                </Link>
            </div>

            <div className="max-w-4xl mx-auto py-20 px-6">
                <div className="mb-16">
                    <h1 className="text-6xl font-black text-black uppercase tracking-tighter italic mb-4">Terms & Conditions</h1>
                    <div className="h-4 w-40 bg-primary border-2 border-black"></div>
                    <p className="mt-8 text-black font-bold opacity-60 uppercase tracking-widest text-xs">Last Updated: JANUARY 2026</p>
                </div>

                <div className="space-y-8 text-black leading-relaxed">
                    <p className="text-sm font-medium">
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>

                    <p className="text-sm font-medium">
                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <span className="font-black">www.ncetbuddy.in</span> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                    </p>

                    <p className="text-sm font-medium">
                        The Platform is owned by <span className="font-black">ExamBuddy</span>, a company incorporated under the Companies Act, 1956 with its registered office at <span className="font-black">KOLKATA</span> (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                    </p>

                    <p className="text-sm font-medium">
                        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
                    </p>

                    <div className="p-6 bg-primary/10 border-4 border-black rounded-2xl">
                        <p className="text-sm font-black uppercase">
                            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                        </p>
                    </div>

                    <section>
                        <h2 className="text-2xl font-black uppercase italic mb-4">Terms of Use</h2>

                        <div className="space-y-6">
                            <div>
                                <p className="font-black mb-2">1.</p>
                                <p className="text-sm">To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">2.</p>
                                <p className="text-sm">Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">3.</p>
                                <p className="text-sm">Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">4.</p>
                                <p className="text-sm">The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">5.</p>
                                <p className="text-sm">You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">6.</p>
                                <p className="text-sm">You agree to pay us the charges associated with availing the Services.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">7.</p>
                                <p className="text-sm">You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">8.</p>
                                <p className="text-sm">You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">9.</p>
                                <p className="text-sm">You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">10.</p>
                                <p className="text-sm">You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">11.</p>
                                <p className="text-sm">Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">12.</p>
                                <p className="text-sm">These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">13.</p>
                                <p className="text-sm">All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Kolkata.</p>
                            </div>

                            <div>
                                <p className="font-black mb-2">14.</p>
                                <p className="text-sm">All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="mt-20 pt-10 border-t-4 border-black text-center">
                    <Link href="/">
                        <Button className="bg-primary border-4 border-black text-black font-black py-4 px-10 h-auto text-lg shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-1 hover:translate-y-1 transition-all">
                            I UNDERSTAND
                        </Button>
                    </Link>
                </div>
            </div>
        </main>
    );
}
